import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Explicit ordering (api-common pattern). The API Reference is generated into
// docs/api by docusaurus-plugin-typedoc on every build (see docusaurus.config.ts).
const sidebars: SidebarsConfig = {
	docs: [
		'index',
		'getting-started',
		'tailwind-setup',
		'theming',
		'hooks',
		{
			type: 'category',
			label: 'API Reference',
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
	],
}

export default sidebars
