import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Stock shadcn/ui primitives are documented upstream; we surface each as a
// sidebar link straight to its Storybook story (mirrors the catalog table on
// components/index.mdx — keep the two in sync when adding/removing components).
const uiPrimitives: [label: string, storyId: string][] = [
	['Accordion', 'ui-accordion--default'],
	['Alert', 'ui-alert--default'],
	['Alert dialog', 'ui-alertdialog--default'],
	['Aspect ratio', 'ui-aspectratio--default'],
	['Avatar', 'ui-avatar--default'],
	['Badge', 'ui-badge--default'],
	['Breadcrumb', 'ui-breadcrumb--default'],
	['Button', 'ui-button--default'],
	['Button group', 'ui-buttongroup--default'],
	['Calendar', 'ui-calendar--single'],
	['Card', 'ui-card--default'],
	['Carousel', 'ui-carousel--default'],
	['Chart', 'ui-chart--bars'],
	['Checkbox', 'ui-checkbox--default'],
	['Collapsible', 'ui-collapsible--default'],
	['Command', 'ui-command--default'],
	['Context menu', 'ui-contextmenu--default'],
	['Dialog', 'ui-dialog--default'],
	['Drawer', 'ui-drawer--default'],
	['Dropdown menu', 'ui-dropdownmenu--default'],
	['Empty', 'ui-empty--default'],
	['Field', 'ui-field--default'],
	['Form', 'ui-form--default'],
	['Hover card', 'ui-hovercard--default'],
	['Input', 'ui-input--default'],
	['Input group', 'ui-inputgroup--with-leading-icon'],
	['Input OTP', 'ui-inputotp--default'],
	['Item', 'ui-item--default'],
	['Kbd', 'ui-kbd--single'],
	['Label', 'ui-label--default'],
	['Menubar', 'ui-menubar--default'],
	['Navigation menu', 'ui-navigationmenu--default'],
	['Pagination', 'ui-pagination--default'],
	['Popover', 'ui-popover--default'],
	['Progress', 'ui-progress--default'],
	['Radio group', 'ui-radiogroup--default'],
	['Resizable', 'ui-resizable--horizontal'],
	['Scroll area', 'ui-scrollarea--default'],
	['Select', 'ui-select--default'],
	['Separator', 'ui-separator--horizontal'],
	['Sheet', 'ui-sheet--right'],
	['Sidebar', 'ui-sidebar--default'],
	['Skeleton', 'ui-skeleton--default'],
	['Slider', 'ui-slider--default'],
	['Sonner', 'ui-sonner--default'],
	['Spinner', 'ui-spinner--default'],
	['Switch', 'ui-switch--default'],
	['Table', 'ui-table--default'],
	['Tabs', 'ui-tabs--default'],
	['Textarea', 'ui-textarea--default'],
	['Toggle', 'ui-toggle--default'],
	['Toggle group', 'ui-togglegroup--multiple'],
	['Tooltip', 'ui-tooltip--default'],
]

// Explicit ordering (api-common pattern). The API Reference is generated into
// docs/api by docusaurus-plugin-typedoc on every build (see docusaurus.config.ts).
const sidebars: SidebarsConfig = {
	docs: [
		'index',
		'getting-started',
		'tailwind-setup',
		'theming',
		'hooks',
		{
			type: 'category',
			label: 'Components',
			link: { type: 'doc', id: 'components/index' },
			items: [
				{ type: 'autogenerated', dirName: 'components/ui-extended' },
				{
					type: 'category',
					label: 'UI primitives',
					collapsed: true,
					items: uiPrimitives.map(([label, storyId]) => ({
						type: 'link' as const,
						label,
						href: `pathname:///react-common/storybook/?path=/story/${storyId}`,
					})),
				},
			],
		},
		{
			type: 'category',
			label: 'API Reference',
			items: [{ type: 'autogenerated', dirName: 'api' }],
		},
	],
}

export default sidebars
