import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// Explicit categories (api-common pattern). As Components (#8) and the
// TypeDoc API reference (#9) land, add their categories alongside these.
const sidebars: SidebarsConfig = {
	docs: [
		'index',
		{
			type: 'category',
			label: 'Architecture Decisions',
			collapsed: false,
			// Landing page at /docs/adr (the nav "ADRs" link) — auto-lists every record.
			link: {
				type: 'generated-index',
				title: 'Architecture Decision Records',
				description:
					'The significant architectural decisions for react-common — the why behind the structure.',
				slug: '/adr',
			},
			items: [{ type: 'autogenerated', dirName: 'adr' }],
		},
	],
}

export default sidebars
